version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ./wey_backend
      dockerfile: Dockerfile
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
    command:
      ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]

  vue:
    build:
      context: ./wey_frontend
      dockerfile: Dockerfile
    volumes:
      - ./vue:/app
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]

volumes:
  postgres_data:
